services:
  app:
    image: python:3.11.5
    container_name: houzz_scrapper__app
    working_dir: /app
    volumes:
      - .:/app
    build:
      context: .
      dockerfile: Docker/Dockerfile.app
    networks:
      - app_network
    entrypoint: "Docker/app.sh"

  redis:
    image: redis:7
    restart: unless-stopped
    container_name: houzz_scrapper__redis
    networks:
      - app_network

networks:
  app_network:
